#! /usr/bin/bash env

gunzip -c snakemake/outPooled/tc.spi.merged.ctssMaxCounts11.ctssMaxTpm1.bed.gz |\
    md5 > md5checkSum_snakemake_spi
gunzip -c rake/outPooled/tc.spi_merged.ctssMaxCounts11_ctssMaxTpm1.bed.gz | \
    md5 > md5checkSum_rake_spi

md5snakemake=`cat md5checkSum_snakemake_spi`
md5rake=`cat md5checkSum_rake_spi`
if [ "$md5snakemake" = "$md5rake" ]
then
    echo "Spi Files generated by rakefile and snakefile have the same content"
else
    echo "Spi Files generated by rakefile and snakefile do NOT have the same content"
fi

